#!/usr/bin/env python3
"""Download every Google Font the players/pages offer into assets/fonts/ so
visitors' browsers never contact Google (a GDPR issue - see the privacy
notes in worker/README.md's Stats section). Re-run after adding a font to
js/modules/pageTextStyles.js's TEXT_FONT_OPTIONS; the list is read from
there. Only latin + latin-ext subsets are kept - other scripts fall back to
the system font.

Output: assets/fonts/<value>.css (@font-face rules, relative URLs) plus
assets/fonts/<value>/*.woff2. Stdlib only.
"""
import pathlib
import re
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "fonts"
# A modern UA so Google serves woff2 with unicode-range subsets.
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
KEEP_SUBSETS = {"latin", "latin-ext"}

# Inter is also the players' base UI font (css/layout.css), used italic too.
EXTRA_AXES = {"inter": "ital,wght@0,100..900;1,100..900"}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as resp:
        data = resp.read()
    return data if binary else data.decode("utf-8")


def families():
    src = (ROOT / "js/modules/pageTextStyles.js").read_text()
    for m in re.finditer(r'value: "([a-z]+)".*?googleFont: "([^"]+)".*?weights: \[([^\]]+)\]', src):
        value, google, weights = m.group(1), m.group(2), m.group(3)
        family = google.split(":")[0]
        wts = sorted(int(w) for w in re.findall(r'"(\d+)"', weights))
        yield value, family, wts


def css_for(value, family, weights):
    axes = EXTRA_AXES.get(value)
    candidates = [axes] if axes else []
    candidates += [f"wght@{weights[0]}..{weights[-1]}", "wght@" + ";".join(map(str, weights))]
    for spec in candidates:
        try:
            return fetch(f"https://fonts.googleapis.com/css2?family={family}:{spec}&display=swap")
        except urllib.error.HTTPError as e:
            if e.code != 400:  # 400 = not a variable font for that range
                raise
    raise RuntimeError(f"No usable CSS for {family}")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for value, family, weights in families():
        css = css_for(value, family, weights)
        blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
        font_dir = OUT / value
        font_dir.mkdir(exist_ok=True)
        kept = []
        for subset, block in blocks:
            if subset not in KEEP_SUBSETS:
                continue
            url = re.search(r"url\((https://[^)]+)\)", block).group(1)
            style = re.search(r"font-style: (\w+)", block).group(1)
            weight = re.search(r"font-weight: ([\d ]+);", block).group(1).replace(" ", "-")
            name = f"{value}-{style}-{weight}-{subset}.woff2"
            (font_dir / name).write_bytes(fetch(url, binary=True))
            kept.append(f"/* {subset} */\n" + block.replace(url, f"{value}/{name}"))
        (OUT / f"{value}.css").write_text(
            f"/* {family.replace('+', ' ')} - self-hosted from Google Fonts (SIL OFL / Apache 2.0). "
            f"Generated by scripts/self-host-fonts.py - don't hand-edit. */\n" + "\n".join(kept) + "\n"
        )
        print(f"{value}: {len(kept)} files")


if __name__ == "__main__":
    main()
